config/routes.rb
AjaxDemo::Application.routes.draw do
  root :to => "Users#new"

  resource :session
  resources :users do
    resources :secrets
    resource :friendship, only: [:create, :destroy]
  end

  resource :tags, only: [:new, :create]

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :friend_id, :user_id

  belongs_to :user
  belongs_to :friend, class_name: "User", foreign_key: :friend_id

end

app/models/secret.rb
class Secret < ActiveRecord::Base
  attr_accessible :title, :author_id, :recipient_id, :tag_ids

  belongs_to :author, :class_name => "User"
  belongs_to :recipient, :class_name => "User"
  has_many :tags, through: :secret_taggings
  has_many :secret_taggings

  validates :title, :author, :recipient, :presence => true
end

app/models/secret_tagging.rb
class SecretTagging < ActiveRecord::Base
  attr_accessible :secret_id, :tag_id

  belongs_to :secret
  belongs_to :tag

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :title

  has_many :secret_taggings
  has_many :secrets, through: :secret_taggings
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password
  attr_reader :password

  has_many(
    :authored_secrets,
    :class_name => "Secret",
    :foreign_key => "author_id"
  )
  has_many(
    :received_secrets,
    :class_name => "Secret",
    :foreign_key => "recipient_id"
  )

  has_many :friendships, foreign_key: :user_id
  has_many :friends, through: :friendships, source: :friend

  validates :username, :password_digest, :presence => true

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    params[:friendship] ||= {}
    params[:friendship][:friend_id] = params[:user_id]
    params[:friendship][:user_id] = current_user.id
    @friend = Friendship.new(params[:friendship])
    @friend.save

    respond_to do |format|
      format.json {render json: "success".to_json}
    end
  end

  def destroy
    @friend = Friendship.find_by_user_id_and_friend_id(current_user.id, params[:user_id])
    @friend.destroy
    respond_to do |format|
      format.json {render json: "success".to_json}
    end
  end

end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  def index
    respond_to do |format|
      format.html { render :index }
      format.json { render :json => Secret.all }
    end
  end

  def create
    params[:secret][:author_id] = current_user.id
    params[:secret][:recipient_id] = params[:user_id]
    @secret = Secret.create!(params[:secret])

    respond_to do |format|
      format.json { render :json => @secret }
    end
  end

  def new
    @secret = Secret.new()
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user_attributes = params[:user]
    @user = login_user(
      user_attributes[:username],
      user_attributes[:password]
    )
    
    if @user
      redirect_to user_url(@user)
    else
      @user = User.new(user_attributes)
      render :new
    end
  end

  def new
    @user = User.new
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(params[:tag])
    @tag.save
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.create(params[:user])
    redirect_to user_url(@user)
  end

  def new
    @user = User.new
    @friends = current_user.friends
  end

  def show
    @user = User.find(params[:id])
    @tags = Tag.all
  end

  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    return nil if session[:session_token].nil?

    User.find_by_session_token(session[:session_token])
  end

  def login_user(username, password)
    u = User.find_by_username(username)

    return nil if u.nil?
    return nil unless BCrypt::Password.new(u.password_digest) == password

    u.session_token = SecureRandom::urlsafe_base64(32)
    u.save!
    session[:session_token] = u.session_token

    u
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/destroy.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <style type="text/css">

  .hidden{
    visibility: hidden;
  }

  </style>
  <title>AjaxDemo</title>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<% if current_user %>
<%= current_user.username %>
<% end %>

<body>
  <%= yield %>
</body>
</html>

app/views/secrets/_form.html.erb
<script type="application/json" id="alltags">
  <%= tags.to_json.html_safe %>
</script>

<form class="newsecret" action="<%= user_secrets_url(@user.id) %>">

  <input type="text" name="secret[title]">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" class="creation" value="Create Secret">

  <div id="insert_select_template">
    <button class="addtag">Add More Tags!</button>
  </div>

</form>


<script type="text/template" id="add_select_template">
  <select name="secret[tag_ids][]" class = "something">
  <%% for (var i = 0; i < info.length; i++) { %>
    <option value="<%%=info[i].id%>"><%%=info[i].title%></option>
    <%% } %>

  </select>
</script>

<script>
//jquery

var templateCode = $("#add_select_template").html()
var templateFn = _.template(templateCode)
console.log(templateFn);
var bootTags = JSON.parse($("#alltags").html())
var info = bootTags.map(function(tag){return {title: tag.title, id: tag.id}});
var newHTML = templateFn({info: info});
console.log(newHTML)

$(document).ready(function(){
  $("#insert_select_template").prepend(newHTML);
});

console.log(newHTML);
$(".addtag").click(function(event){
  event.preventDefault();
  $("#insert_select_template").append(newHTML)
})

</script>

app/views/secrets/new.html.erb
<form action = "<%= user_secrets_url %>" method="post">

  <label for="title">Title</title>
  <input type="text" name="secret[title]">
  <input type="hidden" name="authenticity_token"
  value="<%= form_authenticity_token %>">
  <input type="submit" value="Create new secret">

</form>

app/views/tags/create.html.erb
<h1>Tags#create</h1>
<p>Find me in app/views/tags/create.html.erb</p>

app/views/tags/destroy.html.erb
<h1>Tags#destroy</h1>
<p>Find me in app/views/tags/destroy.html.erb</p>

app/views/tags/new.html.erb
<%= form_for(@tag) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>

  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>

<% included = @friends ? @friends.include?(user) : nil %>

<div class="userform <%= included ? "friended" : "unfriended" %>">
  <%= user.username %>
<form action="<%= user_friendship_url(user) %>" class="friend <%= included ? "hidden" : "" %>">
  <input type="submit" value="friend" class="friend">
</form>
<form action="<%= user_friendship_url(user) %>" class="unfriend <%= included ? "" : "hidden" %>">
  <input type="submit" value="unfriend" class="unfriend">
</form>
</div>

<% end %>

<script>
var friendings = function(friendToggle, oppFriend){
  $(".userform").on("click", "input." + friendToggle, function(event){
    event.preventDefault();
    $(this).attr('disabled','disabled');
    $(this).attr('value', friendToggle + 'ing...');
    var formData = $(this.form).serialize();
    var that = this;
    $.ajax({
      url: that.form.action + ".json",
      type: friendToggle === "friend" ? "POST" : "DELETE",
      data: formData,
      success: function () {
        $(that.form).toggleClass('hidden');
        $(that.form).siblings("." + oppFriend).toggleClass('hidden');
        $(that).removeAttr('disabled');
        $(that).attr('value', friendToggle);
      }
    });
  }
  );
}

friendings('friend', 'unfriend');
friendings('unfriend', 'friend');
</script>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<%= render partial: "secrets/form", locals: {tags: @tags} %>

<ul>
  <% @user.received_secrets.reverse.each do |secret| %>
    <li><%= secret.title %></li>
  <% end %>
</ul>

<script>

$(".newsecret").on("click", "input[class='creation']", function(event) {
  event.preventDefault();
  var formData = $(this.form).serialize();
  var that = this;
  $.ajax({
    url: that.form.action,
    type: "POST",
    data: formData,
    success: function() {
      var secretFormTitle = $(that).siblings("input[type='text']");
      $("ul").prepend("<li style='display:none'>" + secretFormTitle.val() + "</li>");
      $("ul li").slideDown();
      secretFormTitle.val('')
    }
  });
});



</script>